import ChakraDefaultTheme from "@chakra-ui/theme";
import * as Chakra from "@chakra-ui/react";
import Head from "next/head";
import * as React from "react";

const theme = Chakra.extendTheme({
  fonts: {
    heading: `"Noto Sans TC", ${ChakraDefaultTheme.fonts.heading}`,
    body: `"Noto Sans TC", ${ChakraDefaultTheme.fonts.body}`,
  },
});

export default function TaitianApp({ Component, pageProps }) {
  return (
    <React.Fragment>
      <Head>
        <title>台電資訊鏡像站</title>
        <meta name="description" content="Generated by 台電資訊鏡像站" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@100;300;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Chakra.ChakraProvider theme={theme}>
        <Component {...pageProps} />
      </Chakra.ChakraProvider>
    </React.Fragment>
  );
}
