import Head from "next/head";
import useSWR from "swr";
import styles from "../styles/Home.module.css";

function fetcherJson(...args) {
  return fetch(...args).then((r) => r.json());
}

function RawData() {
  const { data, error } = useSWR("/data/raw/loadpara.json", fetcherJson);

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;

  console.log(data);
  return (
    <div>
      <p>
        <b>Static Data</b>: <code>GET /data/raw/loadpara.json</code>
      </p>
      <pre>
        <code>{JSON.stringify(data, null, 2)}</code>
      </pre>
    </div>
  );
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <RawData />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by VERCEL
        </a>
      </footer>
    </div>
  );
}
